export const COLOMBIA_ID = '09b1489a-821f-453f-8bec-b05f0d755318';

export const paises = [
  { id_pais: COLOMBIA_ID, nombre: 'Colombia' },
  { nombre: 'Afganistán' },
  { nombre: 'Albania' },
  { nombre: 'Argelia' },
  { nombre: 'Andorra' },
  { nombre: 'Angola' },
  { nombre: 'Antigua y Barbuda' },
  { nombre: 'Argentina' },
  { nombre: 'Armenia' },
  { nombre: 'Australia' },
  { nombre: 'Austria' },
  { nombre: 'Azerbaiyán' },
  { nombre: 'Bahamas' },
  { nombre: 'Baréin' },
  { nombre: 'Bangladés' },
  { nombre: 'Barbados' },
  { nombre: 'Bielorrusia' },
  { nombre: 'Bélgica' },
  { nombre: 'Belice' },
  { nombre: 'Benín' },
  { nombre: 'Bután' },
  { nombre: 'Bolivia' },
  { nombre: 'Bosnia y Herzegovina' },
  { nombre: 'Botsuana' },
  { nombre: 'Brasil' },
  { nombre: 'Brunéi' },
  { nombre: 'Bulgaria' },
  { nombre: 'Burkina Faso' },
  { nombre: 'Burundi' },
  { nombre: 'Camboya' },
  { nombre: 'Camerún' },
  { nombre: 'Canadá' },
  { nombre: 'Cabo Verde' },
  { nombre: 'República Centroafricana' },
  { nombre: 'Chad' },
  { nombre: 'Chile' },
  { nombre: 'China' },
  { nombre: 'Comoras' },
  { nombre: 'República Democrática del Congo' },
  { nombre: 'República del Congo' },
  { nombre: 'Costa Rica' },
  { nombre: 'Costa de Marfil' },
  { nombre: 'Croacia' },
  { nombre: 'Cuba' },
  { nombre: 'Chipre' },
  { nombre: 'República Checa' },
  { nombre: 'Dinamarca' },
  { nombre: 'Yibuti' },
  { nombre: 'Dominica' },
  { nombre: 'República Dominicana' },
  { nombre: 'Timor Oriental' },
  { nombre: 'Ecuador' },
  { nombre: 'Egipto' },
  { nombre: 'El Salvador' },
  { nombre: 'Guinea Ecuatorial' },
  { nombre: 'Eritrea' },
  { nombre: 'Estonia' },
  { nombre: 'Esuatini' },
  { nombre: 'Etiopía' },
  { nombre: 'Fiyi' },
  { nombre: 'Finlandia' },
  { nombre: 'Francia' },
  { nombre: 'Gabón' },
  { nombre: 'Gambia' },
  { nombre: 'Georgia' },
  { nombre: 'Alemania' },
  { nombre: 'Ghana' },
  { nombre: 'Grecia' },
  { nombre: 'Granada' },
  { nombre: 'Guatemala' },
  { nombre: 'Guinea' },
  { nombre: 'Guinea-Bisáu' },
  { nombre: 'Guyana' },
  { nombre: 'Haití' },
  { nombre: 'Honduras' },
  { nombre: 'Hungría' },
  { nombre: 'Islandia' },
  { nombre: 'India' },
  { nombre: 'Indonesia' },
  { nombre: 'Irán' },
  { nombre: 'Irak' },
  { nombre: 'Irlanda' },
  { nombre: 'Israel' },
  { nombre: 'Italia' },
  { nombre: 'Jamaica' },
  { nombre: 'Japón' },
  { nombre: 'Jordania' },
  { nombre: 'Kazajistán' },
  { nombre: 'Kenia' },
  { nombre: 'Kiribati' },
  { nombre: 'Corea del Norte' },
  { nombre: 'Corea del Sur' },
  { nombre: 'Kosovo' },
  { nombre: 'Kuwait' },
  { nombre: 'Kirguistán' },
  { nombre: 'Laos' },
  { nombre: 'Letonia' },
  { nombre: 'Líbano' },
  { nombre: 'Lesoto' },
  { nombre: 'Liberia' },
  { nombre: 'Libia' },
  { nombre: 'Liechtenstein' },
  { nombre: 'Lituania' },
  { nombre: 'Luxemburgo' },
  { nombre: 'Madagascar' },
  { nombre: 'Malaui' },
  { nombre: 'Malasia' },
  { nombre: 'Maldivas' },
  { nombre: 'Malí' },
  { nombre: 'Malta' },
  { nombre: 'Islas Marshall' },
  { nombre: 'Mauritania' },
  { nombre: 'Mauricio' },
  { nombre: 'México' },
  { nombre: 'Estados Federados de Micronesia' },
  { nombre: 'Moldavia' },
  { nombre: 'Mónaco' },
  { nombre: 'Mongolia' },
  { nombre: 'Montenegro' },
  { nombre: 'Marruecos' },
  { nombre: 'Mozambique' },
  { nombre: 'Birmania' },
  { nombre: 'Namibia' },
  { nombre: 'Nauru' },
  { nombre: 'Nepal' },
  { nombre: 'Países Bajos' },
  { nombre: 'Nueva Zelanda' },
  { nombre: 'Nicaragua' },
  { nombre: 'Níger' },
  { nombre: 'Nigeria' },
  { nombre: 'Noruega' },
  { nombre: 'Omán' },
  { nombre: 'Pakistán' },
  { nombre: 'Palaos' },
  { nombre: 'Panamá' },
  { nombre: 'Papúa Nueva Guinea' },
  { nombre: 'Paraguay' },
  { nombre: 'Perú' },
  { nombre: 'Filipinas' },
  { nombre: 'Polonia' },
  { nombre: 'Portugal' },
  { nombre: 'Catar' },
  { nombre: 'Rumania' },
  { nombre: 'Rusia' },
  { nombre: 'Ruanda' },
  { nombre: 'San Cristóbal y Nieves' },
  { nombre: 'Santa Lucía' },
  { nombre: 'San Vicente y las Granadinas' },
  { nombre: 'Samoa' },
  { nombre: 'San Marino' },
  { nombre: 'Santo Tomé y Príncipe' },
  { nombre: 'Arabia Saudita' },
  { nombre: 'Senegal' },
  { nombre: 'Serbia' },
  { nombre: 'Seychelles' },
  { nombre: 'Sierra Leona' },
  { nombre: 'Singapur' },
  { nombre: 'Eslovaquia' },
  { nombre: 'Eslovenia' },
  { nombre: 'Islas Salomón' },
  { nombre: 'Somalia' },
  { nombre: 'Sudáfrica' },
  { nombre: 'Sudán del Sur' },
  { nombre: 'Sudán' },
  { nombre: 'España' },
  { nombre: 'Sri Lanka' },
  { nombre: 'Surinam' },
  { nombre: 'Suecia' },
  { nombre: 'Suiza' },
  { nombre: 'Siria' },
  { nombre: 'Taiwán' },
  { nombre: 'Tayikistán' },
  { nombre: 'Tanzania' },
  { nombre: 'Tailandia' },
  { nombre: 'Togo' },
  { nombre: 'Tonga' },
  { nombre: 'Trinidad y Tobago' },
  { nombre: 'Túnez' },
  { nombre: 'Turquía' },
  { nombre: 'Turkmenistán' },
  { nombre: 'Tuvalu' },
  { nombre: 'Uganda' },
  { nombre: 'Ucrania' },
  { nombre: 'Emiratos Árabes Unidos' },
  { nombre: 'Reino Unido' },
  { nombre: 'Estados Unidos' },
  { nombre: 'Uruguay' },
  { nombre: 'Uzbekistán' },
  { nombre: 'Vanuatu' },
  { nombre: 'Ciudad del Vaticano' },
  { nombre: 'Venezuela' },
  { nombre: 'Vietnam' },
  { nombre: 'Yemen' },
  { nombre: 'Zambia' },
  { nombre: 'Zimbabue' },
];
